# NVIDIA GPU configuration (Linux only)
x-nvidia-config: &nvidia-config
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: ${GPU_COUNT:-1}
            capabilities: [gpu]


x-common-env: &common-env
  CORS_ORIGINS: ${CORS_ORIGINS:-*}
  MODEL_SCAN_INTERVAL: ${MODEL_SCAN_INTERVAL:-10}
  DEFAULT_INFERENCE_STEPS: ${DEFAULT_INFERENCE_STEPS:-30}
  DEFAULT_GUIDANCE_SCALE: ${DEFAULT_GUIDANCE_SCALE:-7.5}
  PYTHONUNBUFFERED: ${PYTHONUNBUFFERED:-1}
  LOG_LEVEL: ${LOG_LEVEL:-INFO}
  # Authentication settings
  API_KEYS: ${API_KEYS:-test-key-1,test-key-2}
  # Supabase settings (if used)
  SUPABASE_URL: ${SUPABASE_URL:-}
  SUPABASE_KEY: ${SUPABASE_KEY:-}

services:
  # Base service definition (CPU only - works on macOS)
  repnet-manager:
    container_name: repnet-manager
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - ./ai-models:/ai-models:rw
    environment:
      <<: *common-env
    restart: ${RESTART_POLICY:-unless-stopped}
    profiles:
      - default
      - cpu
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # NVIDIA GPU-enabled service
  repnet-manager-nvidia:
    container_name: repnet-manager-nvidia
    extends:
      service: repnet-manager
    <<: *nvidia-config
    profiles:
      - nvidia 