# fly.toml app configuration file generated for repnet-ai-manager on 2025-02-28T14:59:28+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'repnet-ai-manager'
primary_region = 'ord'

[build]

[processes]
manager = 'uv run app.py'
worker = 'uv run celery_worker.py'

[[mounts]]
source = 'ai_models'
destination = '/ai-models'
processes = ['worker']

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1
processes = ['manager']

[checks]
[checks.global_check]
port = 8000
type = 'http'
interval = '15s'
timeout = '10s'
grace_period = '1h0m0s'
method = 'get'
path = '/v1/health'

[[vm]]
size = 'shared-cpu-4x'

[[vm]]
memory = '16gb'
gpu_kind = 'l40s'
processes = ['worker']
