# fly.toml app configuration file generated for repnet-ai-manager on 2025-02-27T17:59:38+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'repnet-ai-manager'
primary_region = 'fra'

[processes]
manager = "uv run app.py"
worker = "uv run celery_worker.py"

[build]

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1
processes = ['manager']

[mounts]
source = "ai_models"
destination = "/ai-models"
processes = ["worker"]

[checks]
[checks.global_check]
grace_period = "60s"
interval = "15s"
method = "get"
path = "/v1/health"
port = 8000
timeout = "10s"
type = "http"

[[vm]]
size = "shared-cpu-4x"

[[vm]]
size = "shared-cpu-2x"
memory = '4gb'
processes = ["worker"]
