# fly.toml app configuration file generated for repnet-ai-manager on 2025-02-27T17:59:38+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'repnet-ai-manager'
primary_region = 'fra'

[build]

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[mounts]
source = "ai_models"
destination = "/ai-models"

[checks]
[checks.global_check]
grace_period = "60s"
interval = "15s"
method = "get"
path = "/v1/health"
port = 8000
timeout = "10s"
type = "http"


[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
