[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path = 'cache_forge'
remappings = [
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "hardhat/=node_modules/hardhat/",
    "@openzeppelin/=node_modules/@openzeppelin/",
]
[fmt]
single_line_statement_blocks = "multi"
sort_imports = true
multiline_func_header = "params_first"
contract_new_lines = true
override_spacing = true
